name: bme_house
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2023.12.12
  - contourpy=1.2.0
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - ghostscript=10.02.1
  - giflib=5.2.1
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=16.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.1
  - pillow=10.0.1
  - pip=23.3.1
  - pyparsing=3.0.9
  - python=3.9.18
  - python-dateutil=2.8.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
